name: Build game PDFs

on:
  push:
    branches: [ "main" ]
    paths:
      - 'games/*.yaml'
      - 'src/*.rs'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build-calendars:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Cargo run
      run: cargo run --release games/*.yaml
      shell: sh

    - name: List all games to GH variable
      run: echo "::set-output name=LS_GAMES::$(ls pdfs | xargs echo | sed 's/.pdf/.pdf,/g' | sed 's/ /\\ /g')"
      id: LS-GAMES

    - name: Check the listed games
      run: echo ${{ steps.LS-GAMES.outputs.LS_GAMES }}
      shell: sh

    - name: Update latest release with new games
      uses: beyarkay/update-existing-release@master
      with:
        token: ${{ github.token }}
        release: Latest card game PDFs
        updateTag: true
        tag: latest
        replace: true
        files: ${{ steps.LS-GAMES.outputs.LS_GAMES }}
        body: "This release contains the latest card games as PDF files"
